{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# ASTRA v1 DEC (Spot-Adaptive Gated Attention Fusion)\n",
    "### SOTA Calibrated Spatial Multi-Omics with Dynamic Gated Fusion & Spatial Potts MRF Consensus DEC\n",
    "\n",
    "This notebook implements **Spot-Adaptive Gated Attention Fusion** within the **ASTRA v1 DEC** spatial multi-omics pipeline:\n",
    "- **Within-Modality Dynamic Gating (RNA Sim vs. Dist)**: Replaces static linear concatenation with a per-spot feature gate $\\mathbf{g}_{\text{spatial}} \\in (0, 1)^{64}$. Spots at tissue boundaries automatically rely on expression similarity, while spots inside uniform tissue layers rely on spatial smoothing.\n",
    "- **Between-Modality Dynamic Gating (RNA vs. ADT/ATAC)**: Learns a cross-modal gate $\\mathbf{g}_{\text{modality}} \\in (0, 1)^{64}$ dynamically balancing protein antibody sensitivity against transcriptomic identity per spot.\n",
    "- **Two-Stage Training Protocol (400 Total Epochs)**: Stage 1 representation pre-training (250 ep) + Bridge state-dict restoration + Stage 2 Spatial Potts Consensus DEC (150 ep).\n",
    "- **Spatial Attention Interpretability**: Extracts and exports $\\mathbf{g}_{\text{modality}}$ to AnnData for publication-quality spatial attention heatmaps.\n",
    "\n",
    "```\n",
    "┌──────────────────────────────────────────────────────────────────────────────────────────────────┐\n",
    "│                         SPOT-ADAPTIVE GATED ATTENTION FUSION ARCHITECTURE                        │\n",
    "│                                                                                                  │\n",
    "│   [Within-Modality Gated Fusion]                                                                 │\n",
    "│   g_spatial = Sigmoid(Linear([Z_sim || Z_dist]))                                                 │\n",
    "│   Z_fused   = g_spatial ⊙ Z_sim + (1 - g_spatial) ⊙ Z_dist                                       │\n",
    "│                                                                                                  │\n",
    "│   [Between-Modality Gated Fusion]                                                                │\n",
    "│   g_modality = Sigmoid(Linear([Z_fused || Z_aux]))                                               │\n",
    "│   Z_final    = g_modality ⊙ Z_fused + (1 - g_modality) ⊙ Z_aux                                    │\n",
    "│                                                                                                  │\n",
    "│   Two-Stage Potts DEC: Bridge Restoration + Soft Student-t + Spatial Potts Consensus Target      │\n",
    "└──────────────────────────────────────────────────────────────────────────────────────────────────┘\n",
    "```\n",
    "\n",
    "> **Hardware Acceleration**: In Google Colab, select **Runtime > Change runtime type > T4 GPU** before executing.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 1: Environment & Package Installation in Colab\n",
    "!pip install -q scanpy anndata scikit-misc rpy2 \"gdown>=5.1.0\" torch_geometric\n",
    "!R -e \"if (!requireNamespace('mclust', quietly=TRUE)) install.packages('mclust', repos='https://cloud.r-project.org')\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 2: Imports & Environment Configuration\n",
    "import os\n",
    "import sys\n",
    "import copy\n",
    "import random\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import scipy\n",
    "import scipy.sparse as sp\n",
    "from typing import Optional, Tuple, Dict, List\n",
    "\n",
    "import sklearn\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "from sklearn.neighbors import NearestNeighbors, kneighbors_graph\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.cluster import KMeans\n",
    "from sklearn.metrics import (\n",
    "    adjusted_rand_score,\n",
    "    normalized_mutual_info_score,\n",
    "    adjusted_mutual_info_score,\n",
    "    homogeneity_score,\n",
    "    v_measure_score,\n",
    "    fowlkes_mallows_score,\n",
    "    silhouette_score,\n",
    "    calinski_harabasz_score,\n",
    "    davies_bouldin_score\n",
    ")\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "from torch_geometric.data import Data\n",
    "from torch_geometric.nn import GCNConv\n",
    "\n",
    "import scanpy as sc\n",
    "import anndata as ad\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f\"[Device] Using compute engine: {device}\")\n",
    "if torch.cuda.is_available():\n",
    "    print(f\"[GPU] Model: {torch.cuda.get_device_name(0)} | Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB\")\n",
    "\n",
    "def set_seed(seed=42):\n",
    "    random.seed(seed)\n",
    "    np.random.seed(seed)\n",
    "    torch.manual_seed(seed)\n",
    "    if torch.cuda.is_available():\n",
    "        torch.cuda.manual_seed(seed)\n",
    "        torch.cuda.manual_seed_all(seed)\n",
    "        torch.backends.cudnn.deterministic = True\n",
    "        torch.backends.cudnn.benchmark = False\n",
    "    os.environ['PYTHONHASHSEED'] = str(seed)\n",
    "\n",
    "set_seed(42)\n",
    "\n",
    "def init_r_mclust():\n",
    "    try:\n",
    "        import rpy2.robjects as robjects\n",
    "        robjects.r['options'](warn=-1)\n",
    "        robjects.r.library(\"mclust\")\n",
    "        return True\n",
    "    except Exception as e:\n",
    "        print(f\"[Warning] R mclust unavailable ({e}). Fallback to KMeans.\")\n",
    "        return False\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 3: Universal Preprocessing Engine\n",
    "def clr_normalize_each_cell(adata, inplace=True):\n",
    "    def seurat_clr(x):\n",
    "        s = np.sum(np.log1p(x[x > 0]))\n",
    "        exp = np.exp(s / len(x)) if len(x) > 0 else 1.0\n",
    "        return np.log1p(x / (exp + 1e-12))\n",
    "\n",
    "    if not inplace:\n",
    "        adata = adata.copy()\n",
    "\n",
    "    X = adata.X.toarray() if sp.issparse(adata.X) else np.array(adata.X)\n",
    "    adata.X = np.apply_along_axis(seurat_clr, 1, X)\n",
    "    return adata\n",
    "\n",
    "def tfidf(X):\n",
    "    idf = X.shape[0] / (X.sum(axis=0) + 1e-12)\n",
    "    if sp.issparse(X):\n",
    "        tf = X.multiply(1.0 / (X.sum(axis=1) + 1e-12))\n",
    "        return sp.csr_matrix(tf.multiply(idf))\n",
    "    else:\n",
    "        tf = X / (X.sum(axis=1, keepdims=True) + 1e-12)\n",
    "        return tf * idf\n",
    "\n",
    "def preprocess_universal(adata_RNA, adata_omics2, dataset_name, n_hvg=3000):\n",
    "    sc.pp.filter_genes(adata_RNA, min_cells=10)\n",
    "    try:\n",
    "        sc.pp.highly_variable_genes(adata_RNA, flavor=\"seurat_v3\", n_top_genes=n_hvg)\n",
    "    except Exception:\n",
    "        sc.pp.normalize_total(adata_RNA, target_sum=1e4)\n",
    "        sc.pp.log1p(adata_RNA)\n",
    "        sc.pp.highly_variable_genes(adata_RNA, flavor=\"seurat\", n_top_genes=n_hvg)\n",
    "\n",
    "    if 'log1p' not in adata_RNA.uns:\n",
    "        sc.pp.normalize_total(adata_RNA, target_sum=1e4)\n",
    "        sc.pp.log1p(adata_RNA)\n",
    "    sc.pp.scale(adata_RNA)\n",
    "\n",
    "    RNA_expression = adata_RNA[:, adata_RNA.var['highly_variable']].X\n",
    "    if sp.issparse(RNA_expression):\n",
    "        RNA_expression = RNA_expression.toarray()\n",
    "\n",
    "    # Second Modality Preprocessing\n",
    "    if dataset_name.startswith(\"10x\"):\n",
    "        # ADT Protein Modality\n",
    "        adata_omics2 = clr_normalize_each_cell(adata_omics2)\n",
    "        sc.pp.scale(adata_omics2)\n",
    "        ADT_expression = adata_omics2.X.toarray() if sp.issparse(adata_omics2.X) else np.array(adata_omics2.X)\n",
    "    else:\n",
    "        # ATAC Epigenomic Modality\n",
    "        adata_omics2.X = tfidf(adata_omics2.X)\n",
    "        sc.pp.normalize_per_cell(adata_omics2, counts_per_cell_after=1e4)\n",
    "        sc.pp.log1p(adata_omics2)\n",
    "        n_comps = min(50, adata_omics2.shape[1])\n",
    "        pca_model = PCA(n_components=n_comps, random_state=42)\n",
    "        X_atac = adata_omics2.X.toarray() if sp.issparse(adata_omics2.X) else adata_omics2.X\n",
    "        ADT_expression = pca_model.fit_transform(X_atac)\n",
    "\n",
    "    return RNA_expression, ADT_expression, adata_RNA, adata_omics2\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 4: Dual-Graph Topology & Spatial Adjacency Construction\n",
    "class DualGraphData(Data):\n",
    "    def __init__(self, x_RNA, x_ADT, sim_edge_index, sim_edge_weight,\n",
    "                 dist_edge_index, dist_edge_weight, common_edge_index, common_edge_weight):\n",
    "        super().__init__()\n",
    "        self.x_RNA = x_RNA\n",
    "        self.x_ADT = x_ADT\n",
    "        self.sim_edge_index = sim_edge_index\n",
    "        self.sim_edge_weight = sim_edge_weight\n",
    "        self.dist_edge_index = dist_edge_index\n",
    "        self.dist_edge_weight = dist_edge_weight\n",
    "        self.common_edge_index = common_edge_index\n",
    "        self.common_edge_weight = common_edge_weight\n",
    "\n",
    "def build_dual_graph(RNA_expression, ADT_expression, cell_positions, device='cpu', num_neighbors=15):\n",
    "    # 1. Cosine Feature Similarity KNN Graph\n",
    "    similarity_matrix = cosine_similarity(RNA_expression)\n",
    "    nbrs = NearestNeighbors(n_neighbors=num_neighbors + 1, metric='cosine').fit(RNA_expression)\n",
    "    _, indices = nbrs.kneighbors(RNA_expression)\n",
    "\n",
    "    adjacency_matrix = np.zeros_like(similarity_matrix, dtype=int)\n",
    "    for i in range(len(RNA_expression)):\n",
    "        for j in indices[i][1:]:\n",
    "            adjacency_matrix[i, j] = 1\n",
    "            adjacency_matrix[j, i] = 1\n",
    "\n",
    "    sim_edge_index = torch.tensor(np.array(np.nonzero(adjacency_matrix)), dtype=torch.long).to(device)\n",
    "    sim_edge_weight = torch.tensor(similarity_matrix[adjacency_matrix > 0], dtype=torch.float).to(device)\n",
    "\n",
    "    # 2. Spatial Distance KNN Graph\n",
    "    knn_graph = kneighbors_graph(cell_positions, n_neighbors=num_neighbors, mode='distance', include_self=False)\n",
    "    knn_graph = knn_graph.maximum(knn_graph.T)\n",
    "    dist_edge_index = torch.tensor(np.array(knn_graph.nonzero()), dtype=torch.long).to(device)\n",
    "    dist_edge_weight = torch.tensor(knn_graph.data, dtype=torch.float).to(device)\n",
    "\n",
    "    # 3. Common Edge Pure Intersection (Consensus)\n",
    "    sim_edges = set(zip(sim_edge_index[0].tolist(), sim_edge_index[1].tolist()))\n",
    "    dist_edges = set(zip(dist_edge_index[0].tolist(), dist_edge_index[1].tolist()))\n",
    "    common_edges = sim_edges.intersection(dist_edges)\n",
    "\n",
    "    common_edge_index = torch.tensor(list(zip(*common_edges)), dtype=torch.long).to(device)\n",
    "    common_edge_weight = torch.ones(common_edge_index.size(1), dtype=torch.float).to(device)\n",
    "\n",
    "    x_RNA = torch.tensor(RNA_expression, dtype=torch.float).to(device)\n",
    "    x_ADT = torch.tensor(ADT_expression, dtype=torch.float).to(device)\n",
    "\n",
    "    return DualGraphData(\n",
    "        x_RNA, x_ADT,\n",
    "        sim_edge_index, sim_edge_weight,\n",
    "        dist_edge_index, dist_edge_weight,\n",
    "        common_edge_index, common_edge_weight\n",
    "    )\n",
    "\n",
    "def compute_spatial_adj_norm(dist_edge_index, num_nodes, device='cpu'):\n",
    "    \"\"\"Construct row-normalized spatial adjacency matrix for Potts MRF consensus.\"\"\"\n",
    "    adj = torch.sparse_coo_tensor(dist_edge_index, torch.ones(dist_edge_index.size(1), device=device), size=(num_nodes, num_nodes)).to_dense()\n",
    "    adj = adj + torch.eye(num_nodes, device=device)\n",
    "    deg = adj.sum(dim=1, keepdim=True)\n",
    "    adj_norm = adj / (deg + 1e-12)\n",
    "    return adj_norm\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 5: Neural Architecture & Gated Attention Fusion Modules\n",
    "class GatedAttentionFusion(nn.Module):\n",
    "    \"\"\"\n",
    "    Spot-Adaptive Gated Attention Fusion Module.\n",
    "    Computes a learned, per-spot, feature-wise attention gate g in (0, 1)^d:\n",
    "        g = Sigmoid(W_g [z1 || z2] + b_g)\n",
    "        z_fused = g ⊙ z1 + (1 - g) ⊙ z2\n",
    "    Followed by an output projection layer to refine the fused manifold.\n",
    "    \"\"\"\n",
    "    def __init__(self, dim: int = 64):\n",
    "        super().__init__()\n",
    "        self.gate_net = nn.Sequential(\n",
    "            nn.Linear(2 * dim, dim),\n",
    "            nn.Sigmoid()\n",
    "        )\n",
    "        self.out_proj = nn.Linear(dim, dim)\n",
    "\n",
    "    def forward(self, z1: torch.Tensor, z2: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:\n",
    "        combined = torch.cat([z1, z2], dim=1)\n",
    "        gate = self.gate_net(combined)\n",
    "        fused = gate * z1 + (1.0 - gate) * z2\n",
    "        fused = self.out_proj(fused)\n",
    "        return fused, gate\n",
    "\n",
    "class SpatialPottsDEC(nn.Module):\n",
    "    \"\"\"\n",
    "    Spatial Potts Markov Random Field Consensus Deep Embedding Clustering (DEC).\n",
    "    Smooths target distribution P using spatial neighborhood consensus to suppress salt-and-pepper noise\n",
    "    while preserving transcriptomic cluster boundaries.\n",
    "    \"\"\"\n",
    "    def __init__(self, num_clusters: int, latent_dim: int = 64, alpha: float = 1.0, lambda_spatial: float = 0.15):\n",
    "        super().__init__()\n",
    "        self.num_clusters = num_clusters\n",
    "        self.latent_dim = latent_dim\n",
    "        self.alpha = alpha\n",
    "        self.lambda_spatial = lambda_spatial\n",
    "        self.cluster_centers = nn.Parameter(torch.Tensor(num_clusters, latent_dim))\n",
    "        nn.init.xavier_uniform_(self.cluster_centers)\n",
    "\n",
    "    def compute_q(self, z: torch.Tensor) -> torch.Tensor:\n",
    "        # Student's t-distribution soft assignment\n",
    "        dist = torch.sum((z.unsqueeze(1) - self.cluster_centers.unsqueeze(0)) ** 2, dim=2)\n",
    "        q = 1.0 / (1.0 + dist / self.alpha)\n",
    "        q = q ** ((self.alpha + 1.0) / 2.0)\n",
    "        q = q / (torch.sum(q, dim=1, keepdim=True) + 1e-12)\n",
    "        return q\n",
    "\n",
    "    def compute_spatial_target_p(self, q: torch.Tensor, spatial_adj_norm: torch.Tensor) -> torch.Tensor:\n",
    "        # Standard DEC target distribution\n",
    "        weight = q ** 2 / (torch.sum(q, dim=0, keepdim=True) + 1e-12)\n",
    "        p_dec = weight / (torch.sum(weight, dim=1, keepdim=True) + 1e-12)\n",
    "\n",
    "        # Spatial Potts neighborhood consensus\n",
    "        spatial_consensus = torch.mm(spatial_adj_norm, q)\n",
    "\n",
    "        # Potts modulated target\n",
    "        p_spatial = p_dec * torch.exp(self.lambda_spatial * spatial_consensus)\n",
    "        p_final = p_spatial / (torch.sum(p_spatial, dim=1, keepdim=True) + 1e-12)\n",
    "        return p_final\n",
    "\n",
    "    def forward(self, z: torch.Tensor, p_target: Optional[torch.Tensor] = None):\n",
    "        q = self.compute_q(z)\n",
    "        if p_target is not None:\n",
    "            kl_loss = F.kl_div(q.log(), p_target, reduction='batchmean')\n",
    "        else:\n",
    "            kl_loss = torch.tensor(0.0, device=z.device)\n",
    "        return q, kl_loss\n",
    "\n",
    "class DualGCN_Gated(nn.Module):\n",
    "    def __init__(self, in_channels, hidden_channels, out_channels, q_dim, dropout=0.0):\n",
    "        super(DualGCN_Gated, self).__init__()\n",
    "        # RNA dual branches (similarity & distance)\n",
    "        self.x_RNA1 = GCNConv(in_channels, hidden_channels)\n",
    "        self.x_RNA2 = GCNConv(in_channels, hidden_channels)\n",
    "        self.protein3 = GCNConv(q_dim, out_channels)\n",
    "\n",
    "        self.sim_conv = GCNConv(hidden_channels, out_channels)\n",
    "        self.dist_conv = GCNConv(hidden_channels, out_channels)\n",
    "\n",
    "        # Spot-Adaptive Gated Attention Fusion Modules\n",
    "        # Fusion 1: Within-Modality (RNA Sim vs. RNA Dist)\n",
    "        self.fusion_layer1 = GatedAttentionFusion(dim=out_channels)\n",
    "        # Fusion 2: Between-Modality (Fused RNA vs. Auxiliary ADT/ATAC)\n",
    "        self.fusion_layer2 = GatedAttentionFusion(dim=out_channels)\n",
    "\n",
    "        # Decoupled Multi-Task Decoders\n",
    "        self.dropout = dropout\n",
    "        self.deconv1 = nn.Linear(out_channels, hidden_channels)\n",
    "        self.deconv2 = nn.Linear(hidden_channels, in_channels)\n",
    "        self.deconv4 = nn.Linear(hidden_channels, q_dim)\n",
    "        self.deconv5 = nn.Linear(hidden_channels, in_channels + q_dim)\n",
    "\n",
    "    def forward(self, x_RNA, x_ADT, sim_edge_index, sim_edge_weight,\n",
    "                dist_edge_index, dist_edge_weight, common_edge_index, common_edge_weight):\n",
    "        xs = F.relu(self.x_RNA1(x_RNA, sim_edge_index, sim_edge_weight))\n",
    "        xs = F.dropout(xs, self.dropout, training=self.training)\n",
    "\n",
    "        xd = F.relu(self.x_RNA2(x_RNA, dist_edge_index, dist_edge_weight))\n",
    "        xd = F.dropout(xd, self.dropout, training=self.training)\n",
    "\n",
    "        x_sim = self.sim_conv(xs, sim_edge_index, sim_edge_weight)\n",
    "        x_dist = self.dist_conv(xd, dist_edge_index, dist_edge_weight)\n",
    "        pro = self.protein3(x_ADT, common_edge_index, common_edge_weight)\n",
    "\n",
    "        # Dynamic Gated Fusion\n",
    "        fused, gate_spatial = self.fusion_layer1(x_sim, x_dist)\n",
    "        fused_pro, gate_modality = self.fusion_layer2(fused, pro)\n",
    "        return x_sim, x_dist, fused, fused_pro, pro, gate_spatial, gate_modality\n",
    "\n",
    "    def reconstruct_joint(self, z):\n",
    "        return self.deconv5(F.relu(self.deconv1(z)))\n",
    "\n",
    "    def reconstruct_rna(self, z):\n",
    "        return self.deconv2(F.relu(self.deconv1(z)))\n",
    "\n",
    "    def reconstruct_aux(self, z):\n",
    "        return self.deconv4(F.relu(self.deconv1(z)))\n",
    "\n",
    "class ASTRA_v1_DEC_Gated(nn.Module):\n",
    "    def __init__(self, in_channels, hidden_channels, out_channels, q_dim, num_clusters,\n",
    "                 beta=25.0, gamma=10.0, delta=1.0, lambda_dec=1.0, lambda_spatial=0.15, dropout=0.0):\n",
    "        super(ASTRA_v1_DEC_Gated, self).__init__()\n",
    "        self.gcn = DualGCN_Gated(in_channels, hidden_channels, out_channels, q_dim, dropout=dropout)\n",
    "        self.dec = SpatialPottsDEC(num_clusters=num_clusters, latent_dim=out_channels, lambda_spatial=lambda_spatial)\n",
    "        self.beta = beta\n",
    "        self.gamma = gamma\n",
    "        self.delta = delta\n",
    "        self.lambda_dec = lambda_dec\n",
    "        self.l1_lambda = 1e-4\n",
    "        self.l2_lambda = 1e-3\n",
    "\n",
    "    def init_cluster_centers(self, centers_numpy):\n",
    "        \"\"\"Initialize DEC prototype centers using KMeans in aligned latent coordinates.\"\"\"\n",
    "        self.dec.cluster_centers.data.copy_(torch.tensor(centers_numpy, dtype=torch.float32, device=self.dec.cluster_centers.device))\n",
    "\n",
    "    def forward(self, data, compute_dec=False, p_target=None):\n",
    "        x_sim, x_dist, fused, fused_pro, pro, gate_sp, gate_mod = self.gcn(\n",
    "            data.x_RNA, data.x_ADT,\n",
    "            data.sim_edge_index, data.sim_edge_weight,\n",
    "            data.dist_edge_index, data.dist_edge_weight,\n",
    "            data.common_edge_index, data.common_edge_weight\n",
    "        )\n",
    "        if compute_dec:\n",
    "            q, kl_loss = self.dec(fused_pro, p_target)\n",
    "            return x_sim, x_dist, fused, fused_pro, pro, q, kl_loss, gate_sp, gate_mod\n",
    "        return x_sim, x_dist, fused, fused_pro, pro, gate_sp, gate_mod\n",
    "\n",
    "    def cosine_similarity(self, emb):\n",
    "        mat = torch.matmul(emb, emb.T)\n",
    "        norm = torch.norm(emb, p=2, dim=1).reshape((emb.shape[0], 1))\n",
    "        mat = torch.div(mat, torch.matmul(norm, norm.T) + 1e-12)\n",
    "        mat = torch.where(torch.isnan(mat), torch.zeros_like(mat), mat)\n",
    "        mat = mat - torch.diag_embed(torch.diag(mat))\n",
    "        return mat\n",
    "\n",
    "    def spatial_regularization_loss(self, emb, dist_edge_index, dist_edge_weight):\n",
    "        num_nodes = emb.size(0)\n",
    "        graph_nei = torch.sparse_coo_tensor(\n",
    "            dist_edge_index,\n",
    "            torch.ones_like(dist_edge_weight),\n",
    "            size=(num_nodes, num_nodes)\n",
    "        ).to_dense()\n",
    "        graph_neg = 1.0 - graph_nei\n",
    "        sim_mat = torch.sigmoid(self.cosine_similarity(emb))\n",
    "        neigh_loss = torch.mul(graph_nei, torch.log(sim_mat + 1e-10)).mean()\n",
    "        neg_loss = torch.mul(graph_neg, torch.log(1.0 - sim_mat + 1e-10)).mean()\n",
    "        return -(neigh_loss + neg_loss) / 2.0\n",
    "\n",
    "    def compute_losses(self, data, sim_z, dist_z, fused_z, fused_pro, pro, kl_loss=None, stage=1):\n",
    "        combined_raw = torch.cat([data.x_RNA, data.x_ADT], dim=1)\n",
    "        l_rec = F.mse_loss(combined_raw, self.gcn.reconstruct_joint(fused_pro))\n",
    "        l_sim = F.mse_loss(data.x_RNA, self.gcn.reconstruct_rna(sim_z))\n",
    "        l_dist = F.mse_loss(data.x_RNA, self.gcn.reconstruct_rna(dist_z))\n",
    "        l_aux = F.mse_loss(data.x_ADT, self.gcn.reconstruct_aux(pro))\n",
    "\n",
    "        l_spatial = self.spatial_regularization_loss(fused_z, data.dist_edge_index, data.dist_edge_weight)\n",
    "\n",
    "        l1_reg = sum(torch.sum(torch.abs(p)) for p in self.parameters())\n",
    "        l2_reg = sum(torch.sum(p ** 2) for p in self.parameters())\n",
    "        reg_loss = self.l1_lambda * l1_reg + self.l2_lambda * l2_reg\n",
    "\n",
    "        # In Stage 2, moderate reconstruction weight so DEC KL divergence actively sharpens clusters\n",
    "        beta_curr = self.beta if stage == 1 else (self.beta * 0.2)\n",
    "        rec_term = beta_curr * (l_rec + l_sim + l_dist + l_aux)\n",
    "        spatial_term = self.gamma * l_spatial\n",
    "        reg_term = self.delta * reg_loss\n",
    "\n",
    "        total_loss = rec_term + spatial_term + reg_term\n",
    "        if stage == 2 and kl_loss is not None:\n",
    "            total_loss = total_loss + self.lambda_dec * kl_loss\n",
    "\n",
    "        return total_loss, l_rec, l_spatial, (kl_loss.item() if kl_loss is not None else 0.0)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 6: Clustering & Two-Stage Training Engine (400 Epochs)\n",
    "def mclust_R(adata_or_embeddings, num_cluster, modelNames='EEE', use_pca=True, n_comps=20, random_seed=42):\n",
    "    np.random.seed(random_seed)\n",
    "    if init_r_mclust():\n",
    "        try:\n",
    "            import rpy2.robjects as robjects\n",
    "            from rpy2.robjects import pandas2ri, default_converter\n",
    "            from rpy2.robjects.conversion import localconverter\n",
    "            robjects.r.library(\"mclust\")\n",
    "            robjects.r[\"set.seed\"](random_seed)\n",
    "            rmclust = robjects.r[\"Mclust\"]\n",
    "\n",
    "            X = np.array(adata_or_embeddings, dtype=np.float64)\n",
    "            if use_pca and X.shape[1] > n_comps:\n",
    "                comps = min(n_comps, X.shape[1], X.shape[0] - 1)\n",
    "                pca_model = PCA(n_components=comps, random_state=random_seed)\n",
    "                X = pca_model.fit_transform(X)\n",
    "\n",
    "            df = pd.DataFrame(X, columns=[f\"PC{i+1}\" for i in range(X.shape[1])])\n",
    "            subset_size = min(300, X.shape[0])\n",
    "            subset_indices = robjects.IntVector(list(np.random.choice(range(1, X.shape[0] + 1), subset_size, replace=False)))\n",
    "            init_list = robjects.ListVector({'subset': subset_indices})\n",
    "\n",
    "            res = None\n",
    "            with localconverter(default_converter + pandas2ri.converter):\n",
    "                try:\n",
    "                    res = rmclust(df, G=num_cluster, modelNames=modelNames, initialization=init_list)\n",
    "                except Exception:\n",
    "                    res = rmclust(df, G=num_cluster)\n",
    "\n",
    "            if res is not None and hasattr(res, 'names') and 'classification' in res.names:\n",
    "                return np.array(res['classification']).astype(int)\n",
    "        except Exception as e:\n",
    "            print(f\"[Notice] mclust fallback ({e}). Using KMeans.\")\n",
    "    from sklearn.cluster import KMeans\n",
    "    return KMeans(n_clusters=num_cluster, n_init=10, random_state=random_seed).fit_predict(adata_or_embeddings)\n",
    "\n",
    "def cluster_embeddings(embeddings, num_clusters, method='kmeans', random_seed=42):\n",
    "    if method == 'mclust':\n",
    "        return mclust_R(embeddings, num_cluster=num_clusters, random_seed=random_seed)\n",
    "    from sklearn.cluster import KMeans\n",
    "    return KMeans(n_clusters=num_clusters, n_init=10, random_state=random_seed).fit_predict(embeddings)\n",
    "\n",
    "def train_model_dec(\n",
    "    model: ASTRA_v1_DEC_Gated,\n",
    "    data: DualGraphData,\n",
    "    spatial_adj_norm: torch.Tensor,\n",
    "    pretrain_epochs: int = 250,\n",
    "    finetune_epochs: int = 150,\n",
    "    lr: float = 1e-3,\n",
    "    num_clusters: int = 10,\n",
    "    tool: str = 'kmeans',\n",
    "    seed: int = 42,\n",
    "    p_update_interval: int = 5\n",
    "):\n",
    "    \"\"\"\n",
    "    Calibrated Two-Stage Training Protocol with Gated Attention Fusion (400 Total Epochs):\n",
    "      - Stage 1 (Epochs 1-250): Multimodal Representation Pre-training with Gated Fusion\n",
    "      - Bridge Transition: Restores model weights to peak Stage-1 state_dict and seeds DEC prototypes\n",
    "      - Stage 2 (Epochs 251-400): Spatial Potts Consensus DEC Fine-Tuning with periodic target freezing\n",
    "      - Returns overall best checkpoint across ALL 400 epochs along with learned attention gates.\n",
    "    \"\"\"\n",
    "    optimizer_stage1 = torch.optim.Adam(model.parameters(), lr=lr)\n",
    "\n",
    "    best_sil = -1.0\n",
    "    best_epoch = -1\n",
    "    best_stage = \"Pre-train\"\n",
    "    best_embeddings = None\n",
    "    best_labels = None\n",
    "    best_imputed_rna = None\n",
    "    best_gates = None\n",
    "    best_model_state_overall = None\n",
    "\n",
    "    best_sil_stage1 = -1.0\n",
    "    best_epoch_stage1 = -1\n",
    "    best_model_state_stage1 = None\n",
    "    best_embeddings_stage1 = None\n",
    "\n",
    "    history = {\n",
    "        'total_loss': [],\n",
    "        'recon_loss': [],\n",
    "        'spatial_loss': [],\n",
    "        'kl_loss': [],\n",
    "        'silhouette': []\n",
    "    }\n",
    "\n",
    "    # =========================================================================\n",
    "    # STAGE 1: Representation Pre-training (Epochs 1 to 250)\n",
    "    # =========================================================================\n",
    "    print(f\"\\n{'='*75}\\n[Stage 1/2] Gated Fusion Pre-training ({pretrain_epochs} Epochs | {tool})\\n{'='*75}\")\n",
    "    for epoch in range(pretrain_epochs):\n",
    "        model.train()\n",
    "        optimizer_stage1.zero_grad()\n",
    "        sim_z, dist_z, fused_z, fused_pro, pro, g_sp, g_mod = model(data, compute_dec=False)\n",
    "        loss, l_rec, l_sp, _ = model.compute_losses(data, sim_z, dist_z, fused_z, fused_pro, pro, stage=1)\n",
    "        loss.backward()\n",
    "        optimizer_stage1.step()\n",
    "\n",
    "        # Evaluation mode\n",
    "        model.eval()\n",
    "        with torch.no_grad():\n",
    "            sim_z_eval, dist_z_eval, fused_z_eval, fused_pro_eval, pro_eval, g_sp_eval, g_mod_eval = model(data, compute_dec=False)\n",
    "            epoch_emb = fused_pro_eval.cpu().numpy()\n",
    "\n",
    "        epoch_labels = cluster_embeddings(epoch_emb, num_clusters, method=tool, random_seed=seed)\n",
    "        try:\n",
    "            sil = float(silhouette_score(epoch_emb, epoch_labels))\n",
    "        except Exception:\n",
    "            sil = -1.0\n",
    "\n",
    "        history['total_loss'].append(loss.item())\n",
    "        history['recon_loss'].append(l_rec.item())\n",
    "        history['spatial_loss'].append(l_sp.item())\n",
    "        history['kl_loss'].append(0.0)\n",
    "        history['silhouette'].append(sil)\n",
    "\n",
    "        if sil > best_sil:\n",
    "            best_sil = sil\n",
    "            best_epoch = epoch + 1\n",
    "            best_stage = \"Pre-train\"\n",
    "            best_embeddings = epoch_emb.copy()\n",
    "            best_labels = epoch_labels.copy()\n",
    "            best_gates = (g_sp_eval.cpu().numpy(), g_mod_eval.cpu().numpy())\n",
    "            best_model_state_overall = copy.deepcopy(model.state_dict())\n",
    "            with torch.no_grad():\n",
    "                best_imputed_rna = model.gcn.reconstruct_rna(sim_z_eval).cpu().numpy()\n",
    "\n",
    "        if sil > best_sil_stage1:\n",
    "            best_sil_stage1 = sil\n",
    "            best_epoch_stage1 = epoch + 1\n",
    "            best_model_state_stage1 = copy.deepcopy(model.state_dict())\n",
    "            best_embeddings_stage1 = epoch_emb.copy()\n",
    "\n",
    "        if (epoch + 1) % 25 == 0 or epoch == 0 or (epoch + 1) == pretrain_epochs:\n",
    "            print(f\"Pretrain Ep {epoch+1:3d}/{pretrain_epochs} | Loss: {loss.item():.4f} | Recon: {l_rec.item():.4f} | Sil: {sil:.4f} (Best: {best_sil:.4f} @ Ep {best_epoch})\")\n",
    "\n",
    "    # =========================================================================\n",
    "    # BRIDGE: Restore Peak Stage-1 Weights & Seed Aligned DEC Prototypes\n",
    "    # =========================================================================\n",
    "    print(f\"\\n[Bridge Transition] Restoring peak Stage-1 model weights (Sil = {best_sil_stage1:.4f} @ Ep {best_epoch_stage1})...\")\n",
    "    if best_model_state_stage1 is not None:\n",
    "        model.load_state_dict(best_model_state_stage1)\n",
    "\n",
    "    model.eval()\n",
    "    with torch.no_grad():\n",
    "        _, _, _, fused_pro_best, _, _, _ = model(data, compute_dec=False)\n",
    "        best_emb_aligned = fused_pro_best.cpu().numpy()\n",
    "\n",
    "    kmeans_init = KMeans(n_clusters=num_clusters, n_init=20, random_state=seed)\n",
    "    kmeans_init.fit(best_emb_aligned)\n",
    "    model.init_cluster_centers(kmeans_init.cluster_centers_)\n",
    "    print(\"DEC Cluster Prototypes successfully initialized in aligned latent space!\")\n",
    "\n",
    "    # =========================================================================\n",
    "    # STAGE 2: Spatial Potts Consensus DEC Fine-Tuning (Epochs 251 to 400)\n",
    "    # =========================================================================\n",
    "    lr_stage2 = lr * 0.1  # Dedicated gentle fine-tuning rate (1e-4)\n",
    "    optimizer_stage2 = torch.optim.Adam(model.parameters(), lr=lr_stage2)\n",
    "    p_target = None\n",
    "\n",
    "    print(f\"\\n{'='*75}\\n[Stage 2/2] Gated Spatial Potts Consensus DEC Fine-Tuning ({finetune_epochs} Epochs | lr={lr_stage2:.1e})\\n{'='*75}\")\n",
    "    for epoch in range(finetune_epochs):\n",
    "        curr_epoch = pretrain_epochs + epoch + 1\n",
    "        model.train()\n",
    "\n",
    "        # Periodic target distribution update (T=5)\n",
    "        if epoch % p_update_interval == 0 or p_target is None:\n",
    "            with torch.no_grad():\n",
    "                _, _, _, f_pro_curr, _, _, _ = model(data, compute_dec=False)\n",
    "                q_curr = model.dec.compute_q(f_pro_curr)\n",
    "                p_target = model.dec.compute_spatial_target_p(q_curr, spatial_adj_norm)\n",
    "\n",
    "        optimizer_stage2.zero_grad()\n",
    "        sim_z, dist_z, fused_z, fused_pro, pro, q, kl_loss, g_sp, g_mod = model(data, compute_dec=True, p_target=p_target)\n",
    "        loss, l_rec, l_sp, kl_val = model.compute_losses(data, sim_z, dist_z, fused_z, fused_pro, pro, kl_loss=kl_loss, stage=2)\n",
    "        loss.backward()\n",
    "        optimizer_stage2.step()\n",
    "\n",
    "        # Direct GPU DEC Evaluation\n",
    "        model.eval()\n",
    "        with torch.no_grad():\n",
    "            sim_z_eval, dist_z_eval, fused_z_eval, fused_pro_eval, pro_eval, g_sp_eval, g_mod_eval = model(data, compute_dec=False)\n",
    "            q_eval = model.dec.compute_q(fused_pro_eval)\n",
    "            epoch_emb = fused_pro_eval.cpu().numpy()\n",
    "            preds_q = q_eval.argmax(dim=1).cpu().numpy()\n",
    "\n",
    "        n_unique_q = len(np.unique(preds_q))\n",
    "        if n_unique_q >= 2:\n",
    "            try:\n",
    "                sil_q = float(silhouette_score(epoch_emb, preds_q))\n",
    "            except Exception:\n",
    "                sil_q = -1.0\n",
    "        else:\n",
    "            sil_q = -1.0\n",
    "\n",
    "        try:\n",
    "            km_preds = KMeans(n_clusters=num_clusters, n_init=5, random_state=seed).fit_predict(epoch_emb)\n",
    "            sil_km = float(silhouette_score(epoch_emb, km_preds))\n",
    "        except Exception:\n",
    "            sil_km = -1.0\n",
    "\n",
    "        # Pick superior clustering partition\n",
    "        if sil_q >= sil_km and n_unique_q >= 2:\n",
    "            sil = sil_q\n",
    "            epoch_labels = preds_q\n",
    "        else:\n",
    "            sil = sil_km\n",
    "            epoch_labels = km_preds\n",
    "\n",
    "        history['total_loss'].append(loss.item())\n",
    "        history['recon_loss'].append(l_rec.item())\n",
    "        history['spatial_loss'].append(l_sp.item())\n",
    "        history['kl_loss'].append(kl_val)\n",
    "        history['silhouette'].append(sil)\n",
    "\n",
    "        if sil > best_sil:\n",
    "            best_sil = sil\n",
    "            best_epoch = curr_epoch\n",
    "            best_stage = \"DEC-Potts\"\n",
    "            best_embeddings = epoch_emb.copy()\n",
    "            best_labels = epoch_labels.copy()\n",
    "            best_gates = (g_sp_eval.cpu().numpy(), g_mod_eval.cpu().numpy())\n",
    "            best_model_state_overall = copy.deepcopy(model.state_dict())\n",
    "            with torch.no_grad():\n",
    "                best_imputed_rna = model.gcn.reconstruct_rna(sim_z_eval).cpu().numpy()\n",
    "\n",
    "        if (epoch + 1) % 25 == 0 or epoch == 0 or (epoch + 1) == finetune_epochs or sil > best_sil_stage1:\n",
    "            print(f\"DEC Ep {epoch+1:3d}/{finetune_epochs} (Total {curr_epoch:3d}) | Loss: {loss.item():.4f} | KL: {kl_val:.4f} | Sil: {sil:.4f} (Peak: {best_sil:.4f} [{best_stage}] @ Ep {best_epoch})\")\n",
    "\n",
    "    if best_model_state_overall is not None:\n",
    "        model.load_state_dict(best_model_state_overall)\n",
    "\n",
    "    print(f\"\\n{'='*75}\\n[Best Overall Checkpoint] Highest Silhouette = {best_sil:.4f} achieved in [{best_stage}] at Epoch {best_epoch}.\\n{'='*75}\")\n",
    "    return best_embeddings, best_labels, best_imputed_rna, best_gates, best_epoch, best_stage, history\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 7: Dataset Directory & Automatic Download Resolver\n",
    "CHOICES = [\n",
    "    (\"10x_human_lymph_node_A1\", \"https://drive.google.com/drive/folders/10z1N4MwW8Y49o8GlkYGBKVx1N7fiMuyC\"),\n",
    "    (\"10x_human_lymph_node_D1\", \"https://drive.google.com/drive/folders/1-g_Ca2XMaMXF-MisuVY-wobWDX86O6zz\"),\n",
    "    (\"Mouse_Brain_E11_S1\", \"https://drive.google.com/drive/folders/1zRwDJrYnks0LRzlAVRqPU7jE_OcStgPo\"),\n",
    "    (\"Mouse_Brain_E13_S1\", \"https://drive.google.com/drive/folders/1GOufwIRjjfcd9Bi2GKtebzKoPCg2jVud\"),\n",
    "    (\"Mouse_Brain_E15_S1\", \"https://drive.google.com/drive/folders/1rHkTL5OF5qPsEERypRGMS51SjUQ69tdD\"),\n",
    "    (\"Mouse_Brain_E18_S1\", \"https://drive.google.com/drive/folders/1Xj1LNIAY93biS6JIMKNRODn5GvtCKADB\"),\n",
    "]\n",
    "\n",
    "def resolve_dataset_files(dataset_name: str, folder_url: str):\n",
    "    candidate_dirs = [\n",
    "        f\"data/{dataset_name}\",\n",
    "        f\"/content/data/{dataset_name}\",\n",
    "        f\"/content/drive/MyDrive/Colab/data/{dataset_name}\",\n",
    "        f\"/content/drive/MyDrive/Colab/ARISE/data/{dataset_name}\",\n",
    "        f\"/content/drive/MyDrive/Colab/{dataset_name}\"\n",
    "    ]\n",
    "    base_dir = None\n",
    "    for c_dir in candidate_dirs:\n",
    "        if os.path.exists(c_dir):\n",
    "            base_dir = c_dir\n",
    "            break\n",
    "\n",
    "    if base_dir is None:\n",
    "        base_dir = f\"data/{dataset_name}\"\n",
    "        os.makedirs(base_dir, exist_ok=True)\n",
    "        print(f\"Downloading dataset {dataset_name} using gdown...\")\n",
    "        os.system(f'gdown --folder \"{folder_url}\" --output \"{base_dir}\"')\n",
    "\n",
    "    rna_path = os.path.join(base_dir, \"adata_RNA.h5ad\")\n",
    "    if dataset_name.startswith(\"10x\"):\n",
    "        aux_path = os.path.join(base_dir, \"adata_ADT.h5ad\")\n",
    "        anno_path = os.path.join(base_dir, \"annotation.csv\")\n",
    "        gt_col = \"manual-anno\"\n",
    "    else:\n",
    "        aux_path = os.path.join(base_dir, \"adata_ATAC.h5ad\")\n",
    "        anno_path = os.path.join(base_dir, \"anno.csv\")\n",
    "        gt_col = \"cluster\"\n",
    "\n",
    "    if not (os.path.exists(rna_path) and os.path.exists(aux_path) and os.path.exists(anno_path)):\n",
    "        print(f\"Re-downloading {dataset_name}...\")\n",
    "        os.system(f'gdown --folder \"{folder_url}\" --output \"{base_dir}\"')\n",
    "\n",
    "    return rna_path, aux_path, anno_path, gt_col\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 8: Global Configuration & Execution Loop (Gated Fusion 400 Epochs)\n",
    "DATASET_INDICES = [0, 1, 2, 3, 4, 5]       # Choose datasets: [0], [0, 1], etc.\n",
    "SEEDS = [42, 1234, 2024]                   # Benchmark seeds\n",
    "TOOL = 'kmeans'                            # Pretrain evaluation tool ('kmeans' or 'mclust')\n",
    "PRETRAIN_EPOCHS = 250                      # Stage 1: Representation pre-training\n",
    "FINETUNE_EPOCHS = 150                      # Stage 2: Spatial Potts Consensus DEC\n",
    "LAMBDA_DEC = 1.0                           # Calibrated weight of DEC KL divergence loss\n",
    "LAMBDA_SPATIAL = 0.15                      # Tempered spatial Potts consensus strength\n",
    "LR = 1e-3                                  # Stage 1 learning rate (Stage 2 uses 1e-4)\n",
    "OUTPUT_DIR = \"ASTRA_v1_DEC_Gated_outputs\"\n",
    "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
    "\n",
    "all_results = []\n",
    "all_histories = {}\n",
    "\n",
    "for d_idx in DATASET_INDICES:\n",
    "    dataset_name, folder_url = CHOICES[d_idx]\n",
    "    print(f\"\\n{'#'*80}\\n STARTING DATASET: {dataset_name} (Gated Attention Fusion)\\n{'#'*80}\")\n",
    "\n",
    "    rna_path, aux_path, anno_path, gt_col = resolve_dataset_files(dataset_name, folder_url)\n",
    "    adata_RNA = sc.read_h5ad(rna_path)\n",
    "    adata_aux = sc.read_h5ad(aux_path)\n",
    "    anno_df = pd.read_csv(anno_path, index_col=0)\n",
    "\n",
    "    # Safe ground truth extraction\n",
    "    gt_values = anno_df[gt_col] if isinstance(anno_df[gt_col], pd.Series) else anno_df[gt_col].iloc[:, 0]\n",
    "    adata_RNA.obs['ground_truth'] = gt_values.values\n",
    "    adata_aux.obs['ground_truth'] = gt_values.values\n",
    "\n",
    "    RNA_data, ADT_data, adata_RNA, adata_aux = preprocess_universal(adata_RNA, adata_aux, dataset_name)\n",
    "    cell_positions = adata_RNA.obsm['spatial']\n",
    "    graph_data = build_dual_graph(RNA_data, ADT_data, cell_positions, device=device)\n",
    "\n",
    "    spatial_adj_norm = compute_spatial_adj_norm(graph_data.dist_edge_index, RNA_data.shape[0], device=device)\n",
    "    n_clusters = int(adata_RNA.obs['ground_truth'].dropna().nunique())\n",
    "    print(f\"[+] Ground Truth Spatial Domains: {n_clusters} clusters\")\n",
    "\n",
    "    for seed in SEEDS:\n",
    "        print(f\"\\n{'-'*65}\\n Dataset: {dataset_name} | Seed: {seed} | Gated Potts DEC (400 Ep)\\n{'-'*65}\")\n",
    "        set_seed(seed)\n",
    "\n",
    "        model = ASTRA_v1_DEC_Gated(\n",
    "            in_channels=RNA_data.shape[1],\n",
    "            hidden_channels=512,\n",
    "            out_channels=64,\n",
    "            q_dim=ADT_data.shape[1],\n",
    "            num_clusters=n_clusters,\n",
    "            beta=25.0,\n",
    "            gamma=10.0,\n",
    "            delta=1.0,\n",
    "            lambda_dec=LAMBDA_DEC,\n",
    "            lambda_spatial=LAMBDA_SPATIAL\n",
    "        ).to(device)\n",
    "\n",
    "        best_emb, best_labels, best_imputed_rna, best_gates, best_ep, best_stg, hist = train_model_dec(\n",
    "            model=model,\n",
    "            data=graph_data,\n",
    "            spatial_adj_norm=spatial_adj_norm,\n",
    "            pretrain_epochs=PRETRAIN_EPOCHS,\n",
    "            finetune_epochs=FINETUNE_EPOCHS,\n",
    "            lr=LR,\n",
    "            num_clusters=n_clusters,\n",
    "            tool=TOOL,\n",
    "            seed=seed,\n",
    "            p_update_interval=5\n",
    "        )\n",
    "\n",
    "        y_true = adata_RNA.obs['ground_truth'].astype(str)\n",
    "        y_pred = best_labels.astype(str)\n",
    "\n",
    "        ari = float(adjusted_rand_score(y_true, y_pred))\n",
    "        nmi = float(normalized_mutual_info_score(y_true, y_pred))\n",
    "        ami = float(adjusted_mutual_info_score(y_true, y_pred))\n",
    "        homo = float(homogeneity_score(y_true, y_pred))\n",
    "        v_meas = float(v_measure_score(y_true, y_pred))\n",
    "        fmi = float(fowlkes_mallows_score(y_true, y_pred))\n",
    "        sil = float(silhouette_score(best_emb, best_labels))\n",
    "        chi = float(calinski_harabasz_score(best_emb, best_labels))\n",
    "        dbi = float(davies_bouldin_score(best_emb, best_labels))\n",
    "\n",
    "        print(f\"\\n[Final Result] {dataset_name} | Seed {seed} -> ARI: {ari:.4f} | NMI: {nmi:.4f} | AMI: {ami:.4f} | Sil: {sil:.4f} | Best Ep: {best_ep} [{best_stg}]\")\n",
    "\n",
    "        if dataset_name not in all_histories:\n",
    "            all_histories[dataset_name] = {}\n",
    "        all_histories[dataset_name][seed] = hist\n",
    "\n",
    "        all_results.append({\n",
    "            'dataset': dataset_name,\n",
    "            'seed': seed,\n",
    "            'tool': TOOL,\n",
    "            'ARI': ari,\n",
    "            'NMI': nmi,\n",
    "            'AMI': ami,\n",
    "            'Homogeneity': homo,\n",
    "            'V-Measure': v_meas,\n",
    "            'FMI': fmi,\n",
    "            'Silhouette': sil,\n",
    "            'CHI': chi,\n",
    "            'DBI': dbi,\n",
    "            'best_epoch': best_ep,\n",
    "            'best_stage': best_stg\n",
    "        })\n",
    "\n",
    "    # Dataset Summary across all seeds: Mean ± Standard Deviation\n",
    "    dataset_rows = [r for r in all_results if r['dataset'] == dataset_name]\n",
    "    df_d = pd.DataFrame(dataset_rows)\n",
    "    metrics_to_report = ['ARI', 'NMI', 'AMI', 'Homogeneity', 'V-Measure', 'FMI', 'Silhouette', 'CHI', 'DBI']\n",
    "\n",
    "    print(f\"\\n{'='*80}\")\n",
    "    print(f\" DATASET BENCHMARK SUMMARY (Mean ± Std over {len(SEEDS)} Seeds): {dataset_name} (Gated Fusion)\")\n",
    "    print(f\"{'='*80}\")\n",
    "    for m in metrics_to_report:\n",
    "        if m in df_d.columns:\n",
    "            m_mean = df_d[m].mean()\n",
    "            m_std = df_d[m].std()\n",
    "            print(f\"  • {m:<14}: {m_mean:8.4f} ± {m_std:7.4f}\")\n",
    "    print(f\"{'='*80}\\n\")\n",
    "\n",
    "    # Save AnnData outputs\n",
    "    adata_hvg = adata_RNA[:, adata_RNA.var['highly_variable']].copy()\n",
    "    adata_hvg.obsm['ASTRA_v1_DEC_Gated_emb'] = best_emb\n",
    "    adata_hvg.obs['ASTRA_v1_DEC_Gated_domain'] = pd.Categorical(best_labels.astype(str))\n",
    "    if best_imputed_rna is not None:\n",
    "        adata_hvg.layers['imputed'] = best_imputed_rna\n",
    "    if best_gates is not None:\n",
    "        g_sp, g_mod = best_gates\n",
    "        adata_hvg.obsm['gate_spatial'] = g_sp\n",
    "        adata_hvg.obsm['gate_modality'] = g_mod\n",
    "        adata_hvg.obs['mean_rna_attention'] = g_mod.mean(axis=1)\n",
    "\n",
    "    adata_hvg.write_h5ad(os.path.join(OUTPUT_DIR, f\"ASTRA_v1_DEC_Gated_adata_{dataset_name}.h5ad\"))\n",
    "\n",
    "    # Update parent adata_RNA\n",
    "    adata_RNA.obsm['ASTRA_v1_DEC_Gated_emb'] = best_emb\n",
    "    adata_RNA.obs['ASTRA_v1_DEC_Gated_domain'] = pd.Categorical(best_labels.astype(str))\n",
    "    if best_imputed_rna is not None:\n",
    "        imputed_full = (adata_RNA.X.toarray() if sp.issparse(adata_RNA.X) else np.array(adata_RNA.X, dtype=np.float32)).copy()\n",
    "        hvg_mask = adata_RNA.var['highly_variable'].values\n",
    "        imputed_full[:, hvg_mask] = best_imputed_rna\n",
    "        adata_RNA.layers['imputed'] = imputed_full\n",
    "\n",
    "    # Biological biomarker discovery on the HVG subset\n",
    "    try:\n",
    "        sc.tl.rank_genes_groups(adata_hvg, groupby='ASTRA_v1_DEC_Gated_domain', layer='imputed', method='wilcoxon')\n",
    "        marker_df = sc.get.rank_genes_groups_df(adata_hvg, group=None)\n",
    "        marker_df.to_csv(os.path.join(OUTPUT_DIR, f\"ASTRA_v1_DEC_Gated_markers_{dataset_name}.csv\"), index=False)\n",
    "    except Exception as e:\n",
    "        print(f\"[Notice] Biomarker discovery: {e}\")\n",
    "\n",
    "df_results = pd.DataFrame(all_results)\n",
    "df_results.to_csv(os.path.join(OUTPUT_DIR, \"ASTRA_v1_DEC_Gated_benchmark_results.csv\"), index=False)\n",
    "print(f\"\\nAll per-seed results saved to {OUTPUT_DIR}/ASTRA_v1_DEC_Gated_benchmark_results.csv\")\n",
    "\n",
    "# Comprehensive Summary Table: Mean ± Std for All Datasets\n",
    "summary_records = []\n",
    "for d_name, group in df_results.groupby('dataset', sort=False):\n",
    "    rec = {'Dataset': d_name, 'Seeds': len(group)}\n",
    "    for m in ['ARI', 'NMI', 'AMI', 'Homogeneity', 'V-Measure', 'FMI', 'Silhouette', 'CHI', 'DBI']:\n",
    "        if m in group.columns:\n",
    "            rec[f\"{m} (Mean ± Std)\"] = f\"{group[m].mean():.4f} ± {group[m].std():.4f}\"\n",
    "    summary_records.append(rec)\n",
    "\n",
    "summary_df = pd.DataFrame(summary_records)\n",
    "summary_csv_path = os.path.join(OUTPUT_DIR, \"ASTRA_v1_DEC_Gated_benchmark_summary_mean_std.csv\")\n",
    "summary_df.to_csv(summary_csv_path, index=False)\n",
    "print(f\"Summary table saved to {summary_csv_path}\\n\")\n",
    "print(\"=== FINAL UNIVERSAL BENCHMARK SUMMARY: Gated Fusion (Mean ± Std across all Datasets) ===\")\n",
    "print(summary_df.to_string(index=False))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 9: Per-Epoch Visual Analytics Suite (Gated Fusion Trajectory)\n",
    "for d_name, seeds_dict in all_histories.items():\n",
    "    fig, axes = plt.subplots(1, 3, figsize=(20, 5))\n",
    "    epochs_total = PRETRAIN_EPOCHS + FINETUNE_EPOCHS\n",
    "    x_epochs = np.arange(1, epochs_total + 1)\n",
    "\n",
    "    # 1. Total & Reconstruction Losses\n",
    "    for s, hist in seeds_dict.items():\n",
    "        axes[0].plot(x_epochs, hist['total_loss'], alpha=0.3, color='#1f77b4')\n",
    "    mean_tot = np.mean([hist['total_loss'] for hist in seeds_dict.values()], axis=0)\n",
    "    axes[0].plot(x_epochs, mean_tot, color='#1f77b4', lw=2.2, label='Total Loss')\n",
    "    axes[0].axvline(x=PRETRAIN_EPOCHS, color='red', linestyle='--', lw=1.5, label='DEC Activated')\n",
    "    axes[0].set_title(f\"{d_name}: Total Loss Trajectory (Gated Fusion)\", fontweight='bold')\n",
    "    axes[0].set_xlabel(\"Epoch\")\n",
    "    axes[0].set_ylabel(\"Loss\")\n",
    "    axes[0].legend()\n",
    "    axes[0].grid(True, alpha=0.25)\n",
    "\n",
    "    # 2. Stage 2 DEC KL Divergence Loss\n",
    "    for s, hist in seeds_dict.items():\n",
    "        axes[1].plot(x_epochs[PRETRAIN_EPOCHS:], hist['kl_loss'][PRETRAIN_EPOCHS:], alpha=0.4, color='#e377c2')\n",
    "    mean_kl = np.mean([hist['kl_loss'][PRETRAIN_EPOCHS:] for hist in seeds_dict.values()], axis=0)\n",
    "    axes[1].plot(x_epochs[PRETRAIN_EPOCHS:], mean_kl, color='#d62728', lw=2.2, label='Potts KL Loss')\n",
    "    axes[1].set_title(f\"{d_name}: Spatial Potts DEC KL Loss\", fontweight='bold')\n",
    "    axes[1].set_xlabel(\"Epoch (Stage 2)\")\n",
    "    axes[1].set_ylabel(\"KL Divergence\")\n",
    "    axes[1].legend()\n",
    "    axes[1].grid(True, alpha=0.25)\n",
    "\n",
    "    # 3. Continuous Silhouette Trajectory across ALL 400 Epochs\n",
    "    for s, hist in seeds_dict.items():\n",
    "        axes[2].plot(x_epochs, hist['silhouette'], alpha=0.35, color='#2ca02c')\n",
    "    mean_sil = np.mean([hist['silhouette'] for hist in seeds_dict.values()], axis=0)\n",
    "    axes[2].plot(x_epochs, mean_sil, color='#2ca02c', lw=2.5, label='Mean Silhouette')\n",
    "    axes[2].axvline(x=PRETRAIN_EPOCHS, color='red', linestyle='--', lw=1.5, label='DEC Activated')\n",
    "\n",
    "    best_mean_ep = int(np.argmax(mean_sil)) + 1\n",
    "    best_mean_sil = float(mean_sil[best_mean_ep - 1])\n",
    "    axes[2].scatter([best_mean_ep], [best_mean_sil], color='red', s=70, zorder=5, label=f'Peak Sil: {best_mean_sil:.4f} @ Ep {best_mean_ep}')\n",
    "    axes[2].set_title(f\"{d_name}: Silhouette Trajectory (Gated Fusion)\", fontweight='bold')\n",
    "    axes[2].set_xlabel(\"Epoch\")\n",
    "    axes[2].set_ylabel(\"Silhouette Score\")\n",
    "    axes[2].legend()\n",
    "    axes[2].grid(True, alpha=0.25)\n",
    "\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 10: Side-by-Side Spatial Domain & Attention Map Visualization\n",
    "fig, axes = plt.subplots(1, 3, figsize=(21, 6))\n",
    "\n",
    "# 1. Ground Truth\n",
    "axes[0].scatter(cell_positions[:, 0], cell_positions[:, 1], c=pd.factorize(adata_RNA.obs['ground_truth'])[0], cmap='tab20', s=24)\n",
    "axes[0].set_title(f\"{dataset_name}: Ground Truth Annotations\", fontsize=13, fontweight='bold')\n",
    "axes[0].invert_yaxis()\n",
    "axes[0].axis('off')\n",
    "\n",
    "# 2. ASTRA Gated Potts DEC Domains\n",
    "axes[1].scatter(cell_positions[:, 0], cell_positions[:, 1], c=pd.factorize(adata_RNA.obs['ASTRA_v1_DEC_Gated_domain'])[0], cmap='tab20', s=24)\n",
    "axes[1].set_title(f\"{dataset_name}: ASTRA Gated-Potts Spatial Domains\", fontsize=13, fontweight='bold')\n",
    "axes[1].invert_yaxis()\n",
    "axes[1].axis('off')\n",
    "\n",
    "# 3. Spatial Modality Attention Heatmap (RNA vs. Protein/ATAC Weight)\n",
    "if 'mean_rna_attention' in adata_hvg.obs:\n",
    "    sc_att = axes[2].scatter(cell_positions[:, 0], cell_positions[:, 1], c=adata_hvg.obs['mean_rna_attention'], cmap='coolwarm', s=24, vmin=0.0, vmax=1.0)\n",
    "    plt.colorbar(sc_att, ax=axes[2], fraction=0.046, pad=0.04, label='RNA Attention Weight (1 - Aux Weight)')\n",
    "    axes[2].set_title(f\"{dataset_name}: Modality Attention Map (RNA vs Aux)\", fontsize=13, fontweight='bold')\n",
    "    axes[2].invert_yaxis()\n",
    "    axes[2].axis('off')\n",
    "\n",
    "plt.suptitle(f\"Spatial Domain & Attention Analysis: {dataset_name}\", fontsize=15, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
   ]
  }
 ],
 "metadata": {
  "accelerator": "GPU",
  "colab": {
   "gpuType": "T4",
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python 3",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
